catalog:
  path: "/Users/dmedvedev/IdeaProjects/gridU_microservices_course/capstone_project/jcpenney_com-ecommerce_sample.csv"
spring:
  application:
    name: catalog-service
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"
logging:
  level:
    com.gridu: DEBUG
